[2019-03-23 02:33:31,857] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 90, in put
    transaksi_detail = Transactions.query.get(get_jwt_claims['id'])
TypeError: 'function' object is not subscriptable
[2019-03-23 02:35:11,757] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 91, in put
    courier = Couriers.query.get(args['pengiriman'])
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1026, in _get_impl
    if len(primary_key_identity) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
[2019-03-23 02:35:59,159] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 91, in put
    courier = Couriers.query.get(args['pengiriman'])
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1026, in _get_impl
    if len(primary_key_identity) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
[2019-03-23 02:36:49,353] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 91, in put
    courier = Couriers.query.get(args['pengiriman'])
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1026, in _get_impl
    if len(primary_key_identity) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
[2019-03-23 02:37:26,228] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 92, in put
    courier = Couriers.query.get(args['pengiriman'])
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/alphatech/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1026, in _get_impl
    if len(primary_key_identity) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
[2019-03-23 02:38:24,082] {/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py:1761} ERROR - Exception on /transaction [PUT]
Traceback (most recent call last):
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alphatech/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 104, in wrapper
    return fn(*args, **kwargs)
  File "/home/alphatech/Documents/BIG/Fase awal/env_eCommerce/eCommerce/blueprints/transaction/resources.py", line 102, in put
    transaksi_detail.pembayaran = bank.nama_bank
AttributeError: 'NoneType' object has no attribute 'nama_bank'
